version: 0.2
env:
  variables:
    VERSION: "1.0"
    IMAGE_REPO_NAME: "ms-payless-test-api"
    AWS_ACCOUNT_ID: "812830320641"
    AWS_DEFAULT_REGION: "eu-west-1"
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entered the install phase...
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 812830320641.dkr.ecr.eu-west-1.amazonaws.com
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image..
      - mvn clean install
      - docker build -t 812830320641.dkr.ecr.eu-west-1.amazonaws.com/ms-payless-test-api:v1.0.0 .
      - printf '{"ImageURI":"%s"}' 812830320641.dkr.ecr.eu-west-1.amazonaws.com/ms-payless-test-api:v1.0.0  > /imageDetail.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image version ...
      - docker push 812830320641.dkr.ecr.eu-west-1.amazonaws.com/ms-payless-test-api:v1.0.0
      - echo Copy appspec.yaml
      - pwd
artifacts:
    files:
      - /imageDetail.json
      - /taskdef.json
      - /appspec.yaml
    discard-paths: yes
